In [54]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx

In [55]:
data = pd.read_csv("C:/Users/Pratham Patil/Analysis data.csv")

In [56]:
data.head()

,title,industry/department,company,skills,responsibility,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,Finance Analyst,Various/Finance,oliver plus,1. Finance experience\n2. Advanced Excel\n3. P...,1. Track labor costs\n2. Analyze timesheets\n3...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Senior Business Financial Analyst,Finance,LRQA Group,1.Power BI\n2.SAP\n3.Microsoft Office\n4.Finan...,1. Improve reporting\n2. Create reports\n3. Bu...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Finance Analyst,Financial Technology and Retail Technology,NCR Atleos,1. Financial Analysis\n2. Pricing\n3. Risk Ass...,1. Bid Profiling\n2. Pricing Guidance\n3. Marg...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Business Finance Analyst,Data Analytics and Experience Design,Techmatters Technologies,1.Tableau/Power BI\n2. Advanced MS Excel\n3. S...,1. Revenue MIS/Dashboard\n2. Data Liaison\n3. ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Senior Finance Analyst-Reporting and Analysis,Professional Services,Ernst & Young,1. Data Analysis\n2. Problem Solving\n3. Accou...,1. Standard Reporting\n2. Issue Resolution\n3....,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
data = data[['title','skills','responsibility']]
data = data.dropna()

In [58]:
data['skills'] = data['skills'].str.split('\n').apply(lambda x: [skill.strip() for skill in x])

In [61]:
soft_skills_list = ['communication', 'teamwork', 'problem solving', 'leadership', 'time management', 'adaptability', 'creativity']
tools_languages_list = ['excel', 'sql', 'python', 'r', 'tableau', 'power bi', 'sap', 'microsoft office', 'javascript', 'java']

In [62]:
def clean_split_skills(skills_str):
    if isinstance(skills_str, str):
        return [skill.strip().lower() for skill in skills_str.split('\n') if skill.strip()]
    return []

In [63]:
def categorize_skills(skills):
    soft_skills = []
    tools_languages = []
    for skill in skills:
        if any(soft_skill in skill for soft_skill in soft_skills_list):
            soft_skills.append(skill)
        elif any(tool in skill for tool in tools_languages_list):
            tools_languages.append(skill)
    return soft_skills, tools_languages